## Load in the data

library(tidyverse)
langs <- read_csv("https://raw.githubusercontent.com/datadesk/la-county-language-analysis/master/los-angeles-county-languages.csv") %>%
  filter(language %in% c("English", "Spanish"))
langs

## Reformat the data

otherdf <- data.frame(cbind(c(1980,1990,2000,2010,2018),c(13,13,13,13,13),
                            c("Other","Other","Other","Other","Other"),
                            c(1,1,1,1,1),c(c(1,1,1,1,1)-(english$percent+spanish$percent)),
                            c(3,3,3,3,3)))
colnames(otherdf) <- c("year","langcode","language","total","percent","rankinyear")
newlangs <- rbind(langs,otherdf)
newlangs$total <- as.numeric(newlangs$percent)

## Create new version of plot

ggplot(newlangs, aes(fill=language,y=total*100,x=factor(year,levels=rev(levels(factor(year)))))) +
  geom_bar(position="fill",stat="identity",width=0.5) +
  coord_flip() +
  scale_fill_manual("Language Spoken", values = c("Spanish" = "steelblue2", 
                                                  "English" = "royalblue4",
                                                  "Other" = "lightgrey")) +
    labs(title="Top languages spoken in L.A.\nCounty homes",
       subtitle = "Percentage of population",
       caption = "Source: IPUMS USA, University of Minnesota") +
  theme(plot.caption = element_text(hjust = 0,color="grey20"),
        plot.subtitle = element_text(color="grey20")) +
  xlab("") +
  ylab("") +
  scale_y_continuous(labels=scales::percent)
